### ISSUE TITLE
Google Drive Link for data not available

### ISSUE THREAD

**Issue by Steve-Tod** [ethz-asl/vgn#1]
Hi, thank you for sharing your code so quickly!

I clicked the data download link, and found "File is in owner's trash". It seems you have moved the file to the trash. Can you share the data again?

**Comment by Steve-Tod** [comment]
BTW, with ros(catkin), the `pip install -e .` would fail, and then vgn is not installed as a package and running `python scripts/generate_data.py -h` would fail since it `import vgn`.

**Comment by mbreyer** [comment]
Ups, that was my mistake, thanks for letting me know! The link should work again :)

The instructions for pip are meant for installing the package on a system without ROS. However, installing `vgn` into a virtual environment using `pip` should also work on a machine that has ROS installed, you will just not be able to use `roslaunch` and `rosrun`.

**Comment by Steve-Tod** [comment]
Thank you for your response! I work on a server without ros. When I run `pip install -e`, I got

![image](https://user-images.githubusercontent.com/26958167/99445328-5e3f4e00-2958-11eb-9995-f411e9584fba.png)

It seems the setup.py needs catkin...

**Comment by mbreyer** [comment]
The `setup.py` script relies on `catkin_pkg`, so you need to install it into your virtual environment as well with `pip install catkin_pkg`. I'll add the package to the requirements. Let me know if this fixes your problem :)

**Comment by Steve-Tod** [comment]
It works, thank you!

**Comment by fedeceola** [comment]
Hi @mbreyer, I just tried to download the data folder .zip and I also get the message "File is in owner's trash". Could you please share the file again? Thanks in advance :)

**Comment by mbreyer** [comment]
Looks like a screw-up from my local sync client. Should be fixed now.

**Comment by fedeceola** [comment]
Downloaded! Thanks :)

**Comment by mbreyer** [comment]
No problem. Thanks for letting me know :)
