### ISSUE TITLE
What is the definition of gripper local frame?

### ISSUE THREAD

**Issue by jxtxwsbn** [ethz-asl/vgn#10]
Hi, I'm confused to understand that orientation is defined by **cross_product(**-normal,(1,0,0)**)**. I think it causes the gripper local frame to be different for each grasping.

**Comment by mbreyer** [comment]
Yes, that is true. However, the goal of that line is to construct any frame whose Z-axis corresponds to the normal. In the next step, the hand is rotated about the normal by `n` angles to create a set of grasp candidates that will be evaluated in simulation. In the end, it is checked whether any of these candidates resulted in a successful grasp to label that point. As long as `n` is large enough, this procedure should always return a grasp if possible.
