### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by ronen85** [ethz-asl/vgn#11]
Hello, when running the grasping example with the following command:
'python scripts/sim_grasp.py --model data/models/vgn_conv.pth --sim-gui'

I get a really weird error: 
```
(vgn) nir1tv@TV2ZOSD15:~/projects/vgn$ python scripts/sim_grasp.py --model data/models/vgn_conv.pth --sim-gui
pybullet build time: May 28 2020 16:37:34
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 470.42.01
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 470.42.01
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
ven = NVIDIA Corporation
  0%|                                                   | 0/100 [00:00<?, ?it/s]
Segmentation fault (core dumped)
```

By using a debugger, it seems that there's a problem in 'get_grid()' method of 'TSDFVolume' class. 
More specifically, in the line:
'voxels = self._volume.extract_voxel_grid().get_voxels()'
the interpreter exits at once.

System:
Ubuntu 20.04
Nvidia GPU 2080 Ti
Python 3.8.10

Any advice will be greatly appreciated. 

Thanks!

**Comment by mbreyer** [comment]
Thanks for reporting, I can reproduce the error. It seems to be due to a change in the newest version of Open3D. Using `open3d==0.12`, the above command runs fine.

**Comment by mbreyer** [comment]
I updated the method that extracts the truncated signed distances from open3d. This should fix the error. You can pull the change from the `corl2020` branch.

**Comment by ronen85** [comment]
> I updated the method that extracts the truncated signed distances from open3d. This should fix the error. You can pull the change from the `corl2020` branch.

Working!
Thanks!
