### ISSUE TITLE
Date generation error

### ISSUE THREAD

**Issue by RIP4KOBE** [ethz-asl/vgn#12]
I would like to ask if anyone has encountered this problem? I run code python scripts/generate_data.py data/raw/foo --scene pile --object-set blocks --num-grasps=200，then this error was reported. I don't know how to fix it, but I suspect there is something wrong with the openmpi @ffurrer ethz-asl
![Vgn_data_generation_error](https://user-images.githubusercontent.com/61570969/128692621-5c001d7d-9231-4e1f-b52d-e70417e4368d.png)

**Comment by aniketghodake10** [comment]
> I would like to ask if anyone has encountered this problem? I run code python scripts/generate_data.py data/raw/foo --scene pile --object-set blocks --num-grasps=200，then this error was reported. I don't know how to fix it, but I suspect there is something wrong with the openmpi @ffurrer ethz-asl ![Vgn_data_generation_error](https://user-images.githubusercontent.com/61570969/128692621-5c001d7d-9231-4e1f-b52d-e70417e4368d.png)

It samples 120 points per scene. In your case, 120//200 = 1 no. of scene will be there. So your data generation is completed successfully, although it is showing 60% . You can keep no. of grasps as multiple of 120, if you want it to be 100%.
