### ISSUE TITLE
tsdf or pc?

### ISSUE THREAD

**Issue by wd117** [ethz-asl/vgn#14]
First i must admit that you have shared a great work, i'm really interested in this so i have read your paper. 
In your paper,you said:
**While point clouds are able to identify object surfaces in space, we believe that the
additional distance-to-surface information provided by a TSDF representation can improve
overall grasp detection performance**
 I can't get it, why do you think tsdf is better than pc?
Hope to get your  help,thanks!

**Comment by mbreyer** [comment]
Hi wd117, the idea was that a TSDF not only encodes information about the object surface itself (like a point cloud), but also whether voxels lie outside or inside an observed surface which could be advantageous for learning grasps. It would be interesting to do a direct comparison to point clouds though.

**Comment by wd117** [comment]
> 

Thanks!
