### ISSUE TITLE
panda_moveit_config 

### ISSUE THREAD

**Issue by wukongwong** [ethz-asl/vgn#17]
Hi there,
When I have roslauch panda_moveit_config move_group.lanch, I always have the errors and warning below:

![image](https://user-images.githubusercontent.com/21072179/160080201-72a16ecb-a63d-4af7-9438-7e655c15557b.png)
Can anyone have the same issue?
Cheers,

**Comment by wukongwong** [comment]
I found I just have not updated the roscore. Sorry about it.

**Comment by wukongwong** [comment]
I found I just have not updated the roscore. Sorry about it.

**Comment by mbreyer** [comment]
Nice, I just used the latest version of the official [panda_moveit_config repository](https://github.com/ros-planning/panda_moveit_config).
