### ISSUE TITLE
Maybe TSDF resolution setting bug in data generation

### ISSUE THREAD

**Issue by Daiqy** [ethz-asl/vgn#18]
Hi there, 
I am using your scripts to generate data. I am wondering why the TSDF resolution is set to 120 in https://github.com/ethz-asl/vgn/blob/fdd46109ce38a526ed7e2d52336e07e7f0204f17/scripts/generate_data.py#L50, but set to 40 in construct_dataset.py and network training. Is it a bug?
Looking forward to your reply. Thank you!

**Comment by aniketghodake10** [comment]
> Hi there, I am using your scripts to generate data. I am wondering why the TSDF resolution is set to 120 in
> 
> https://github.com/ethz-asl/vgn/blob/fdd46109ce38a526ed7e2d52336e07e7f0204f17/scripts/generate_data.py#L50
> 
> , but set to 40 in construct_dataset.py and network training. Is it a bug?
> Looking forward to your reply. Thank you!

120 resolution is used only for sampling the point from point cloud, i guess it's for better sampling. While constructing the dataset, 40 resolution is used, i guess it's for reducing the computational power while training.

**Comment by mbreyer** [comment]
Thanks for the answer @aniketghodake10, that was exactly the reason. The lower resolution was chosen to decrease the computational and memory requirements of the network, while the higher resolution enables more accurate sampling for generating the training data.
