### ISSUE TITLE
TSDF get_grid gives color€[0,1] and not signed distance

### ISSUE THREAD

**Issue by aniketghodake10** [ethz-asl/vgn#19]
How can we know from colour value whether perticular voxel is outside the surface, on the surface or inside the surface ?

Signed distance could have helped. Any way we can get the signed distance of every voxel ??

**Comment by aniketghodake10** [comment]
Does color value=0.5 mean the voxel is very near to surface ?? And >0.5 means voxel is outside the surface??

**Comment by mbreyer** [comment]
The [Open3D implementation](https://github.com/isl-org/Open3D/blob/fc06aabdb4a12e5c5073513209b59546e3e67d08/cpp/open3d/pipelines/integration/UniformTSDFVolume.cpp#L264) scales the distance values from `[-sdf_trunc, sdf_trunc]` to `[0, 1]`. So yes, a value of 0.5 means the voxel lies on the surface and values >0.5 correspond to outside voxels.

**Comment by Fanqyu** [comment]
> The [Open3D implementation](https://github.com/isl-org/Open3D/blob/fc06aabdb4a12e5c5073513209b59546e3e67d08/cpp/open3d/pipelines/integration/UniformTSDFVolume.cpp#L264) scales the distance values from `[-sdf_trunc, sdf_trunc]` to `[0, 1]`. So yes, a value of 0.5 means the voxel lies on the surface and values >0.5 correspond to outside voxels.

Hi, thanks for the explanation.
However, I found that values > 0.5 correspond to inside voxels, and values < 0.5 just correspond to outside. Am I right?
Looking forward to your reply!
