### ISSUE TITLE
Do the pile and packed scenes need to be trained separately?

### ISSUE THREAD

**Issue by Daiqy** [ethz-asl/vgn#21]
Hi there,
I notice that there are two types of scene, "pile" and "packed", as mentioned in the paper. Do the pile and packed scenes data need to be trained separately to obtain two different VGN models? Or is it a mix of data from these two scenes ("2 million grasps" as mentioned in the paper) to train a full VGN model?
Looking forward to your reply. Thank you!

**Comment by aniketghodake10** [comment]
> Hi there, I notice that there are two types of scene, "pile" and "packed", as mentioned in the paper. Do the pile and packed scenes data need to be trained separately to obtain two different VGN models? Or is it a mix of data from these two scenes ("2 million grasps" as mentioned in the paper) to train a full VGN model? Looking forward to your reply. Thank you!

I guess the pre-trained model is trained on combined pile+packed dataset

**Comment by mbreyer** [comment]
Yes, I split the training data roughly half-half between the two types of scenes.
