### ISSUE TITLE
data.zip - link not working

### ISSUE THREAD

**Issue by Geryyy** [ethz-asl/vgn#30]
Can't download data.zip at the link provided in README.md. 
I get the note that the zip file is in the garbage bin.

**Comment by anmakon** [comment]
Same for me! 
In case you need a workaround, you could download the folder via the commandline using wget:

`wget "https://drive.google.com/uc?export=download&id=1MysYHve3ooWiLq12b58Nm8FWiFBMH-bJ"`

**Comment by mbreyer** [comment]
Sorry about that, the issue should be fixed now. And thanks for the workaround in the meantime @anmakon.
