### ISSUE TITLE
Specific Implementation of Data Augmentation

### ISSUE THREAD

**Issue by kianyale** [ethz-asl/vgn#32]
Hi, thanks for your great work. 
"Samples are augmented with random rotations of multiples of 90° about the gravity vector and random offsets along the z axis."
I wonder when finishing random augmentation, how to decide the sample is positive one or negative one.

**Comment by mbreyer** [comment]
Hi, the label does not change since the code applies the same transform to both the voxel grid and the grasp pose. So the resulting sample still represents the same grasp.

**Comment by kianyale** [comment]
Thanks for your reply!
OK, I see.  From my understanding, this is kind of like randomly rotating the robot around the workspace. Am I right in understanding this way？

**Comment by mbreyer** [comment]
More like randomly rotating the robot and the workspace. Like rotating the reference coordinate frame of the whole thing.

**Comment by kianyale** [comment]
Thanks for your explanation.
I got it. But, I still have a little confusion. Isn't this equivalent to copying a piece of data? Because rotating the reference coordinate frame of the whole thing seems like nothing has changed. Compared with data augmentation of image such as random rotation, random crop or random resize, etc, which are very intuitive to understand, the augmentation of this data really confuses me.
