### ISSUE TITLE
Implementing vgn to other robot arms

### ISSUE THREAD

**Issue by Ginga-Kennis** [ethz-asl/vgn#34]
Hello. Thank you for sharing such a wonderful work. 
I have a universal robot(ur5e) with a gripper and realsense camera mounted on it. I would like to use vgn with this ur5e setup. 
Is there a python script that doesn't include all the panda arm setups and only includes codes that takes multiple depth images as input and outputs the selected grasps? If not, I would like to create that script for my self. Can you specify which python script and config files are necessary to do this.  
Looking forward to your reply!

**Comment by LZzzin1** [comment]
Hello, I also want to skip the simulation and use the image directly to get the capture result, how to achieve it？

**Comment by Ginga-Kennis** [comment]
HI @LZzzin1 
Sorry for late response.
I successfully implemented vgn to UR5e. 
This is the link to the code. 
https://github.com/Ginga-Kennis/vgn/tree/devel
Checkout to the devel branch and see scripts/ur5e_grasp.py for detail.

**Comment by ZJU-PLP** [comment]
> HI @LZzzin1 Sorry for late response. I successfully implemented vgn to UR5e. This is the link to the code. https://github.com/Ginga-Kennis/vgn/tree/devel Checkout to the devel branch and see scripts/ur5e_grasp.py for detail.

@Ginga-Kennis Hi, this link is empty. Could you mind sharing the newly updated link？

**Comment by Ginga-Kennis** [comment]
@ZJU-PLP 

Apologies for the confusion caused earlier. I have updated the repository. 
Please check this link: https://github.com/Ginga-Kennis/vgn_ur5e.

**Comment by ZJU-PLP** [comment]
> @ZJU-PLP
> 
> Apologies for the confusion caused earlier. I have updated the repository. Please check this link: https://github.com/Ginga-Kennis/vgn_ur5e.

Ok, I see. Thanks a lot.
