### ISSUE TITLE
No module named 'sensor_msgs'

### ISSUE THREAD

**Issue by Steve-Tod** [ethz-asl/vgn#4]
Hi, I try to visualize the data by running the code in data.ipynb. I installed `rospy` by `conda install -c conda-forge ros-rospy`.

However, I got the following errors: `No module named 'sensor_msgs'`. Also the `visualization_msgs` and the `geometry_msgs` were not found. It seems these packages are from ros. How can I have them installed?

**Comment by mbreyer** [comment]
Hi, unfortunately you need a full ROS installation to use `rviz`. One could have a look at MayaVi as an alternative, though I have litte experience with it.
