### ISSUE TITLE
ImportError: No module named franka_control.msg

### ISSUE THREAD

**Issue by zhengshuai1** [ethz-asl/vgn#6]
hi, I use python2.7, ubuntu18.04, and ros melodic. I meet the following error: 
(dp2.7) hp@hp:~/graspdemo_ws/src/vgn$ python scripts/panda_grasp.py --model data/models/vgn_conv.pth
pybullet build time: May 28 2020 16:33:28
Traceback (most recent call last):
  File "scripts/panda_grasp.py", line 24, in <module>
    from vgn.utils.panda_control import PandaCommander
  File "/home/hp/graspdemo_ws/src/vgn/src/vgn/utils/panda_control.py", line 3, in <module>
    import franka_control.msg
ImportError: No module named franka_control.msg

**Comment by fkendlessly** [comment]
hi, I also encountered the same problem as you. How did you solve it?

**Comment by fkendlessly** [comment]
it's now all under franka_msgs.msg since 0.5.0
